### ISSUE TITLE
cauta employee

### ISSUE THREAD

**Issue by ionutincau** [ionutincau/Premium#41]
am incercat sa caut dupa emil si nu da nici un rezultat, ar fi fain sa punem sa nu fie case senzitive

**Comment by MariusDK** [comment]
deci tu vrei sa cauti gen si cu Creta si cu creta?

**Comment by MariusDK** [comment]
deci sa fac si cautare dupa email si sa nu fie case senzitive?

**Comment by MariusDK** [comment]
La job mai vrei camp si de locuri maxime?

**Comment by MariusDK** [comment]
rezolvat.
